### PR TITLE
Checks for null input stream on project submission file ACDM-888 #resolve

### PR DESCRIPTION
**Pull request by diutsu**

### CODE REVIEW

**Comment by jcarvalho** [comment]
How will this PR help solve the issue?

First, the only reason that the `InputStream` is null is if the user manually canceled the upload, and even then, this changeset wouldn't prevent a NPE.

**Comment by diutsu** [comment]
The ByteStreams.toByteArray can throw a NPE if 'is' is null.
That was what happened in the external issue associated.

**Comment by jcarvalho** [comment]
I know, you probably missed a `return` or an `else` statement in that `if`, as if the stream is `null`, you're still invoking the `toByteArrayMethod`.

**Comment by diutsu** [comment]
Should be fixed now, thanks.

**Comment by pedrosan7os** [comment]
This should refer to an issue of the same project. FIST-95 is not.

**Pull request merged**
